# Cloud Build configuration for CI/CD
steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']

  # Run tests
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['test']

  # Run linting and type checking
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'typecheck']

  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'check']

  # Build the project
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Deploy to Cloud Functions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'main'
      - '--gen2'
      - '--runtime=nodejs18'
      - '--source=.'
      - '--entry-point=main'
      - '--trigger=http'
      - '--region=${_REGION}'
      - '--set-env-vars=NODE_ENV=${_ENVIRONMENT}'

# Substitution variables
substitutions:
  _REGION: 'asia-northeast1'
  _ENVIRONMENT: 'production'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout
timeout: '1200s'