name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run all checks
      run: |
        npm run typecheck
        npm run check
        npm run test
        npm run build

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}

    - name: Deploy to Cloud Functions
      run: npm run deploy

    - name: Get function URL
      id: get-url
      run: |
        URL=$(gcloud functions describe main --gen2 --region=asia-northeast1 --format="value(serviceConfig.uri)")
        echo "function_url=$URL" >> $GITHUB_OUTPUT

    - name: Test deployed function
      run: |
        curl -f "${{ steps.get-url.outputs.function_url }}" || exit 1

    - name: Comment PR with deployment info
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚀 Deployed to: ${{ steps.get-url.outputs.function_url }}'
          })