name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run all checks
      run: |
        npm run typecheck
        npm run check
        npm run test
        npm run build

    - name: Manual deployment instructions
      run: |
        echo "🚀 Build completed successfully!"
        echo "📝 To deploy manually, run the following commands:"
        echo ""
        echo "1. Authenticate with Google Cloud:"
        echo "   gcloud auth login"
        echo ""
        echo "2. Set your project:"
        echo "   gcloud config set project YOUR_PROJECT_ID"
        echo ""
        echo "3. Deploy the function:"
        echo "   npm run deploy"
        echo ""
        echo "Environment: ${{ github.event.inputs.environment }}"